ejabberd_client_example:
	go build example.go && \
		./example \
		-alsologtostderr=true\
		-notls=true\
		-status="chat"\
		-username="user1@cluster.domain.com"\
		-password="123456"\
		-server="master.domain.com:5222"\
		-debug=false
